start node bot.js
start node .\Pin1\bot.js
start node .\Pin2\bot.js
start node .\Pin3\bot.js
start node .\Pin4\bot.js
start node .\Pin5\bot.js
start node .\Pin6\bot.js
start node .\Pin7\bot.js
start node .\Pin8\bot.js
start node .\Pin9\bot.js
start node .\Pin10\bot.js